# Конспект: библиотека NumPy для Python

# Одномерные массивы

## Создание одномерного массива

In [1]:
import numpy as np

### Создание одномерного массива из списка однородных элементов

In [2]:
array = np.array([1, 2, 3, 4, 5])
display(array)

array([1, 2, 3, 4, 5])

### Создание одномерного массива из переменной, содержащей список однородных элеметов

In [3]:
list = ([1,2,3,4,5])

In [4]:
array_from_list = np.array(list)
display(array_from_list)

array([1, 2, 3, 4, 5])

### Создание одномерного массива используя диапазон значений
numpy.arange(start, end, step)

In [5]:
array_from_range = np.arange(1, 11, 2) 
display(array_from_range)

array([1, 3, 5, 7, 9])

Список может хранить любиые типы данных, например, строки:

In [6]:
orject_array = np.array([1, 2, 3, 6.5, 'Hello world!'])
display(orject_array)

array(['1', '2', '3', '6.5', 'Hello world!'], dtype='<U32')

Тип данных ```dtype='<U32'``` в NumPy обозначает, что массив содержит строки (Unicode) фиксированной длины до 32 символов. Вот более подробное объяснение:  
```<``` Указывает на порядок байтов (little-endian), что означает, что младший байт хранится первым;  
```U``` Обозначает, что элементы массива являются строками Unicode;  
```32``` Максимальная длина каждой строки в массиве составляет 32 символа.

### Создание одномерного массива используя: zeros, ones, full

#### zeros

numpy.zeros(shape)

In [7]:
array_zeros = np.zeros(5)
display(array_zeros)

array([0., 0., 0., 0., 0.])

#### ones

numpy.ones(shape)

In [8]:
array_ones = np.ones(5)
display(array_ones)

array([1., 1., 1., 1., 1.])

#### full

numpy.full(shape, fill_value)

In [9]:
array_digit = np.full(5, 7)
display(array_digit)

array_str = np.full(5, 'x')
display(array_str)

array([7, 7, 7, 7, 7])

array(['x', 'x', 'x', 'x', 'x'], dtype='<U1')

Тип данных ```dtype='<U1'``` обозначает, что массив содержит строки (Unicode) фиксированной длины. В данном случае:  
```<``` указывает на порядок байтов (little-endian);  
```U``` обозначает, что это строки Unicode;  
```1``` указывает максимальную длину каждой строки в массиве (в данном случае 1 символ).  

## Включение данных в одномерный массив - append

```numpy.append(arr, values, axis=None)```  
```arr``` Это входной массив, к которому вы хотите добавить значения.  
```values``` Это значения, которые вы хотите добавить к входному массиву. Форма values должна соответствовать форме arr, за исключением указанной оси.   
```axis``` Этот необязательный параметр указывает ось, вдоль которой будут добавлены значения. Если не указано, массивы будут преобразованы в одномерные, и значения будут добавлены как одномерный массив.

In [10]:
array_example = np.array([1, 2, 3, 4, 5])
display(array_example)

append_example = np.array([6, 7, 8, 9, 10])
display(append_example)

array([1, 2, 3, 4, 5])

array([ 6,  7,  8,  9, 10])

In [11]:
array_example = np.append(array_example, append_example)
display(array_example)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Арифметические операции

In [12]:
arr_1 = np.arange(0,5)
arr_2 = np.arange(6,11)

### Арифметические операции над одномерными массивами

In [13]:
display(f'Исходный массив - {arr_1}')
display(f'Сложение: {arr_1 + 100}')
display(f'Вычитание: {arr_1 - 1}')
display(f'Умножение: {arr_1 * 3}')
display(f'Деление: {arr_1 / 2}')
display(f'Возведение в степень: {arr_1 ** 3}')

'Исходный массив - [0 1 2 3 4]'

'Сложение: [100 101 102 103 104]'

'Вычитание: [-1  0  1  2  3]'

'Умножение: [ 0  3  6  9 12]'

'Деление: [0.  0.5 1.  1.5 2. ]'

'Возведение в степень: [ 0  1  8 27 64]'

### Арифметические операции между одномерными массивами

In [14]:
display(arr_1)
display(arr_2)

array([0, 1, 2, 3, 4])

array([ 6,  7,  8,  9, 10])

In [15]:
display(f'Сложение: {arr_1 + arr_2}')
display(f'Вычитание: {arr_2 - arr_1}')
display(f'Умножение: {arr_1 * arr_2}')
display(f'Деление: {arr_1 / arr_2}')
display(f'Возведение в степень: {arr_1 ** arr_2}')

'Сложение: [ 6  8 10 12 14]'

'Вычитание: [6 6 6 6 6]'

'Умножение: [ 0  7 16 27 40]'

'Деление: [0.         0.14285714 0.25       0.33333333 0.4       ]'

'Возведение в степень: [      0       1     256   19683 1048576]'

**Внимание:** для выполнения арифметических операций между массивами они должны иметь одну размерность.

In [16]:
arr_3 = np.array([1, 2, 3])

In [17]:
display(arr_1)
display(arr_3)

array([0, 1, 2, 3, 4])

array([1, 2, 3])

In [18]:
display(f'Сложение: {arr_1 + arr_3}')
display(f'Вычитание: {arr_2 - arr_3}')
display(f'Умножение: {arr_1 * arr_3}')
display(f'Деление: {arr_1 / arr_3}')
display(f'Возведение в степень: {arr_1 ** arr_3}')

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

Вы полнение будет заершено с ошибкой, т.к. размерность массива arr_1 - 5, а arr_3 всего 3.

## Типы данных в NumPy

### Определение типа данных в массиве

In [20]:
# Создание массива
array = np.array([1, 2, 3, 4, 5])

# Проверка типа самого объекта
print(type(array))  # Это вернет <class 'numpy.ndarray'>

# Проверка типа данных элементов массива, того, что внутри объекта
print(array.dtype)  # Это вернет dtype('int64')


<class 'numpy.ndarray'>
int64


In [24]:
# Сосздадим строковый массив
array = np.array(['1', '2', '3'])

# Првоерим, что теперь хранится в массиве
print(array.dtype) # вернет U1 - т.е. юникод с максимальной длинной в 1 символ

<U1


### Изменение типа данных в массиве

In [25]:
# изменим типа даных в строковом массиве array на целочисленый

print(array.dtype) # вернет U1, т.к пока тип данных еще строковый

# указываем тип данных
array = array.astype(int) 

# првоерим, что тип сменился на целочисленный, integer
print(array.dtype) # вернет int64

<U1
int64


In [34]:
# Работа с типом данных boolean

# создадим массив с парой единиц
ones = np.ones(2)
display(ones) # вернет array([1., 1.])

# создаем массив с нулями
zeros = np.zeros(3)
display(zeros) # вернет array([0., 0., 0.])

# объединим в один массив
array_bool = np.append(ones, zeros)
display(array_bool) # вернет оба массива вместе array([1., 1., 0., 0., 0.]) 

# изменим теперь тип данных на boolean
array_bool = array_bool.astype(bool)
display(array_bool) # вернет array([ True,  True, False, False, False]) 

array([1., 1.])

array([0., 0., 0.])

array([1., 1., 0., 0., 0.])

array([ True,  True, False, False, False])