# Конспект: библиотека NumPy для Python

## Создание одномерного массива

In [1]:
import numpy as np

### Создание одномерного массива из списка однородных элементов

In [2]:
array = np.array([1, 2, 3, 4, 5])
display(array)

array([1, 2, 3, 4, 5])

### Создание одномерного массива из переменной, содержащей список однородных элеметов

In [3]:
list = ([1,2,3,4,5])

In [4]:
array_from_list = np.array(list)
display(array_from_list)

array([1, 2, 3, 4, 5])

### Создание одномерного массива используя диапазон значений
numpy.arange(start, end, step)

In [5]:
array_from_range = np.arange(1, 11, 2) 
display(array_from_range)

array([1, 3, 5, 7, 9])

Список может хранить любиые типы данных, например, строки:

In [6]:
orject_array = np.array([1, 2, 3, 6.5, 'Hello world!'])
display(orject_array)

array(['1', '2', '3', '6.5', 'Hello world!'], dtype='<U32')

Тип данных ```dtype='<U32'``` в NumPy обозначает, что массив содержит строки (Unicode) фиксированной длины до 32 символов. Вот более подробное объяснение:  
```<``` Указывает на порядок байтов (little-endian), что означает, что младший байт хранится первым;  
```U``` Обозначает, что элементы массива являются строками Unicode;  
```32``` Максимальная длина каждой строки в массиве составляет 32 символа.

### Создание одномерного массива используя: zeros, ones, full

#### zeros

numpy.zeros(shape)

In [7]:
array_zeros = np.zeros(5)
display(array_zeros)

array([0., 0., 0., 0., 0.])

#### ones

numpy.ones(shape)

In [8]:
array_ones = np.ones(5)
display(array_ones)

array([1., 1., 1., 1., 1.])

#### full

numpy.full(shape, fill_value)

In [9]:
array_digit = np.full(5, 7)
display(array_digit)

array_str = np.full(5, 'x')
display(array_str)

array([7, 7, 7, 7, 7])

array(['x', 'x', 'x', 'x', 'x'], dtype='<U1')

Тип данных ```dtype='<U1'``` обозначает, что массив содержит строки (Unicode) фиксированной длины. В данном случае:  
```<``` указывает на порядок байтов (little-endian);  
```U``` обозначает, что это строки Unicode;  
```1``` указывает максимальную длину каждой строки в массиве (в данном случае 1 символ).  