# Конспект: библиотека NumPy для Python

## Создание одномерного массива

In [3]:
import numpy as np

### Создание одномерного массива из списка однородных элементов

In [5]:
array = np.array([1, 2, 3, 4, 5])
display(array, type(array))

array([1, 2, 3, 4, 5])

numpy.ndarray

### Создание одномерного массива из переменной, содержащей список однородных элеметов

In [7]:
list = ([1,2,3,4,5])

In [8]:
array_from_list = np.array(list)
display(array_from_list, type(array_from_list))

array([1, 2, 3, 4, 5])

numpy.ndarray

### Создание одномерного массива используя диапазон значений
numpy.arange(start, end, step)

In [10]:
array_from_range = np.arange(1, 11, 2) 
display(array_from_range, type(array_from_range))

array([1, 3, 5, 7, 9])

numpy.ndarray

Список может хранить любиые типы данных, например, строки:

In [12]:
orject_array = np.array([1, 2, 3, 6.5, 'Hello world!'])
display(orject_array, type(orject_array))

array(['1', '2', '3', '6.5', 'Hello world!'], dtype='<U32')

numpy.ndarray

dtype='<U32' - весь массив теерь хранит в себе только строки

In [20]:
test


NameError: name 'test' is not defined