# Конспект: библиотека NumPy для Python

# Одномерные массивы

## Создание одномерного массива

In [1]:
import numpy as np

### Создание одномерного массива из списка

In [2]:
array = np.array([1, 2, 3, 4, 5])
display(array)

array([1, 2, 3, 4, 5])

### Создание одномерного массива из переменной

In [3]:
list = ([1,2,3,4,5])

In [4]:
array_from_list = np.array(list)
display(array_from_list)

array([1, 2, 3, 4, 5])

### Создание одномерного массива используя диапазон значений
numpy.arange(start, end, step)

In [5]:
array_from_range = np.arange(1, 11, 2) 
display(array_from_range)

array([1, 3, 5, 7, 9])

Список может хранить любиые типы данных, например, строки:

In [6]:
orject_array = np.array([1, 2, 3, 6.5, 'Hello world!'])
display(orject_array)

array(['1', '2', '3', '6.5', 'Hello world!'], dtype='<U32')

Тип данных ```dtype='<U32'``` в NumPy обозначает, что массив содержит строки (Unicode) фиксированной длины до 32 символов. Вот более подробное объяснение:  
```<``` Указывает на порядок байтов (little-endian), что означает, что младший байт хранится первым;  
```U``` Обозначает, что элементы массива являются строками Unicode;  
```32``` Максимальная длина каждой строки в массиве составляет 32 символа.

### Создание одномерного массива используя: zeros, ones, full

#### zeros

numpy.zeros(shape)

In [7]:
array_zeros = np.zeros(5)
display(array_zeros)

array([0., 0., 0., 0., 0.])

#### ones

numpy.ones(shape)

In [8]:
array_ones = np.ones(5)
display(array_ones)

array([1., 1., 1., 1., 1.])

#### full

numpy.full(shape, fill_value)

In [9]:
array_digit = np.full(5, 7)
display(array_digit)

array_str = np.full(5, 'x')
display(array_str)

array([7, 7, 7, 7, 7])

array(['x', 'x', 'x', 'x', 'x'], dtype='<U1')

Тип данных ```dtype='<U1'``` обозначает, что массив содержит строки (Unicode) фиксированной длины. В данном случае:  
```<``` указывает на порядок байтов (little-endian);  
```U``` обозначает, что это строки Unicode;  
```1``` указывает максимальную длину каждой строки в массиве (в данном случае 1 символ).  

## Включение данных в одномерный массив - append

```numpy.append(arr, values, axis=None)```  
```arr``` Это входной массив, к которому вы хотите добавить значения.  
```values``` Это значения, которые вы хотите добавить к входному массиву. Форма values должна соответствовать форме arr, за исключением указанной оси.   
```axis``` Этот необязательный параметр указывает ось, вдоль которой будут добавлены значения. Если не указано, массивы будут преобразованы в одномерные, и значения будут добавлены как одномерный массив.

In [10]:
array_example = np.array([1, 2, 3, 4, 5])
display(array_example)

append_example = np.array([6, 7, 8, 9, 10])
display(append_example)

array([1, 2, 3, 4, 5])

array([ 6,  7,  8,  9, 10])

In [11]:
array_example = np.append(array_example, append_example)
display(array_example)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Арифметические операции

In [12]:
arr_1 = np.arange(0,5)
arr_2 = np.arange(6,11)

### Арифметические операции над одномерными массивами

In [13]:
display(f'Исходный массив - {arr_1}')
display(f'Сложение: {arr_1 + 100}')
display(f'Вычитание: {arr_1 - 1}')
display(f'Умножение: {arr_1 * 3}')
display(f'Деление: {arr_1 / 2}')
display(f'Возведение в степень: {arr_1 ** 3}')

'Исходный массив - [0 1 2 3 4]'

'Сложение: [100 101 102 103 104]'

'Вычитание: [-1  0  1  2  3]'

'Умножение: [ 0  3  6  9 12]'

'Деление: [0.  0.5 1.  1.5 2. ]'

'Возведение в степень: [ 0  1  8 27 64]'

### Арифметические операции между одномерными массивами

In [14]:
display(arr_1)
display(arr_2)

array([0, 1, 2, 3, 4])

array([ 6,  7,  8,  9, 10])

In [15]:
display(f'Сложение: {arr_1 + arr_2}')
display(f'Вычитание: {arr_2 - arr_1}')
display(f'Умножение: {arr_1 * arr_2}')
display(f'Деление: {arr_1 / arr_2}')
display(f'Возведение в степень: {arr_1 ** arr_2}')

'Сложение: [ 6  8 10 12 14]'

'Вычитание: [6 6 6 6 6]'

'Умножение: [ 0  7 16 27 40]'

'Деление: [0.         0.14285714 0.25       0.33333333 0.4       ]'

'Возведение в степень: [      0       1     256   19683 1048576]'

**Внимание:** для выполнения арифметических операций между массивами они должны иметь одну размерность.

In [16]:
arr_3 = np.array([1, 2, 3])

In [17]:
display(arr_1)
display(arr_3)

array([0, 1, 2, 3, 4])

array([1, 2, 3])

display(f'Сложение: {arr_1 + arr_3}')
display(f'Вычитание: {arr_2 - arr_3}')
display(f'Умножение: {arr_1 * arr_3}')
display(f'Деление: {arr_1 / arr_3}')
display(f'Возведение в степень: {arr_1 ** arr_3}')

Вы полнение будет заершено с ошибкой, т.к. размерность массива arr_1 - 5, а arr_3 всего 3.

# Типы данных в NumPy

### Определение типа данных в массиве

In [18]:
# Создание массива
array = np.array([1, 2, 3, 4, 5])

# Проверка типа самого объекта
print(type(array))  # Это вернет <class 'numpy.ndarray'>

# Проверка типа данных элементов массива, того, что внутри объекта
print(array.dtype)  # Это вернет dtype('int64')


<class 'numpy.ndarray'>
int64


In [19]:
# Сосздадим строковый массив
array = np.array(['1', '2', '3'])

# Првоерим, что теперь хранится в массиве
print(array.dtype) # вернет U1 - т.е. юникод с максимальной длинной в 1 символ

<U1


### Изменение типа данных в массиве

In [20]:
# изменим типа даных в строковом массиве array на целочисленый

print(array.dtype) # вернет U1, т.к пока тип данных еще строковый

# указываем тип данных
array = array.astype(int) 

# првоерим, что тип сменился на целочисленный, integer
print(array.dtype) # вернет int64

<U1
int64


In [21]:
# Работа с типом данных boolean

# создадим массив с парой единиц
ones = np.ones(2)
display(ones) # вернет array([1., 1.])

# создаем массив с нулями
zeros = np.zeros(3)
display(zeros) # вернет array([0., 0., 0.])

# объединим в один массив
array_bool = np.append(ones, zeros)
display(array_bool) # вернет оба массива вместе array([1., 1., 0., 0., 0.]) 

# изменим теперь тип данных на boolean
array_bool = array_bool.astype(bool)
display(array_bool) # вернет array([ True,  True, False, False, False]) 

array([1., 1.])

array([0., 0., 0.])

array([1., 1., 0., 0., 0.])

array([ True,  True, False, False, False])

# Многомерные массивы

## Создание многомерного массива из переменной

In [22]:

# Создадим объект python (список списков)
lst_1 = ([[1, 2, 3,], [4, 5, 6]])

# выведем результат
print(f'Содержимое объекта: {lst_1}, \n'
      f'Тип объекта: {type(lst_1)}')

# создадим массив из переменной
arr_1 = np.array(lst_1).astype(str) # для практики изменим тип данных на str

# выведем результат
print('\nМассив:\n', arr_1)
print('Тип данных в массиве:', arr_1.dtype)

Содержимое объекта: [[1, 2, 3], [4, 5, 6]], 
Тип объекта: <class 'list'>

Массив:
 [['1' '2' '3']
 ['4' '5' '6']]
Тип данных в массиве: <U21


## Создание многомерного массива в ручном режиме

# создадим многомерный массив в ручном режиме
arr_2 = np.array([
                    [1.5, 2.3, 1.1],     # 3 элемента
                    [3.1, 2.5, 11, 6.1]  # 4 элемента
])

Такой скрипт вернет нам ошибку. Причина заключается в том, что все уровни многомерного массива должны содержать равное число элеметонв. Исправим наш код.

In [23]:
arr_2 = np.array([
                    [1.5, 2.3, 1.1],     
                    [3.1, 2.5, 11] 
])

display(arr_2, arr_2.dtype)

array([[ 1.5,  2.3,  1.1],
       [ 3.1,  2.5, 11. ]])

dtype('float64')

При изменении типа данных у числел с плавающей точкой на целочисленный тип, значения будут округлены вниз, т.е. дробная часть будет просто отсечена.

In [24]:
arr_3 = arr_2.astype(int)
display(arr_3, arr_3.dtype)

array([[ 1,  2,  1],
       [ 3,  2, 11]])

dtype('int64')

## Создание многомерных массивов: zeros, ones, full, range

### zeros

In [25]:
# создадим многомерный массив
arr_zeros = np.zeros([2, 3]).astype(int) # изменим тип данных на int
    # где 2 и 3 - размерность массив
       # 2 - число элементов массива
       # количество значений внутри элемента массива

display(arr_zeros, arr_zeros.dtype)

array([[0, 0, 0],
       [0, 0, 0]])

dtype('int64')

### ones

In [26]:
# логика аналогична zeros
arr_ones = np.ones([2, 3]).astype(int)
display(arr_ones, arr_ones.dtype)

array([[1, 1, 1],
       [1, 1, 1]])

dtype('int64')

### full

In [27]:
# создадим многомерный массив используя full
arr_full = np.full([3, 5], 7)
    # где 3 и 5 это значения размерности массива
        # 7 - то, чем мы заполняем этот массив

display(arr_full, arr_full.dtype)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

dtype('int64')

### range

In [28]:
# создаем одномерный массив используя range
arr_range = np.array(range(10))
print(f'Изначальфынй массив')
print(f'{arr_range} \n')

# меняем форму массива используя reshape
arr_reshape = arr_range.reshape(2, 5)
print(f'Измененный массив')
print(arr_reshape)

Изначальфынй массив
[0 1 2 3 4 5 6 7 8 9] 

Измененный массив
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Арифметические операции

### Арифметические операции над многомерными массивам

In [29]:

# создадим массив
array_test = np.array(range(9)).reshape(3, 3)

# взглянем на результат
print(array_test)
print(f'Тип данных в массиве: {array_test.dtype}')

# выполним стандартные арифметические дедйствия над многомерным массивом
print(f'\n Умножение')
print(f'{array_test * 2}')

print(f'\n Деление')
print(f'{array_test / 2}')
print('При делении тип автоматически преобразуется во float')

print(f'\n Сложение')
print(f'{array_test + 100}')

print(f'\n Вычитание')
print(f'{array_test - 0.33}')

print(f'\n Возведение в степень')
print(f'{array_test ** 3}')

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Тип данных в массиве: int64

 Умножение
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]

 Деление
[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]
При делении тип автоматически преобразуется во float

 Сложение
[[100 101 102]
 [103 104 105]
 [106 107 108]]

 Вычитание
[[-0.33  0.67  1.67]
 [ 2.67  3.67  4.67]
 [ 5.67  6.67  7.67]]

 Возведение в степень
[[  0   1   8]
 [ 27  64 125]
 [216 343 512]]


### Арифметические операции между многомерными массивами

In [30]:
# для демонстарции создадим два массива
arr_a = np.full((3, 5), 100)
arr_b = np.full((3, 5), 33)

# выведем наши массивы
print(f'Массив а: \n {arr_a}')
print(f'\n Массив b: \n {arr_b}')

Массив а: 
 [[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]

 Массив b: 
 [[33 33 33 33 33]
 [33 33 33 33 33]
 [33 33 33 33 33]]


***Внимание!*** Для выполнения арифметических действий между массивами, их размерность должна быть одинаковой.

In [31]:
# выполним традиционные арифметические действия

print(f'\n Умножение')
print(f'{arr_a * arr_b}')

print(f'\n Деление')
print(f'{arr_a / arr_b}')
print('При делении тип автоматически преобразуется во float')

print(f'\n Сложение')
print(f'{arr_a + arr_b}')

print(f'\n Вычитание')
print(f'{arr_a - arr_b}')

print(f'\n Возведение в степень')
print(f'{arr_b ** arr_a}')


 Умножение
[[3300 3300 3300 3300 3300]
 [3300 3300 3300 3300 3300]
 [3300 3300 3300 3300 3300]]

 Деление
[[3.03030303 3.03030303 3.03030303 3.03030303 3.03030303]
 [3.03030303 3.03030303 3.03030303 3.03030303 3.03030303]
 [3.03030303 3.03030303 3.03030303 3.03030303 3.03030303]]
При делении тип автоматически преобразуется во float

 Сложение
[[133 133 133 133 133]
 [133 133 133 133 133]
 [133 133 133 133 133]]

 Вычитание
[[67 67 67 67 67]
 [67 67 67 67 67]
 [67 67 67 67 67]]

 Возведение в степень
[[-8877898876394183551 -8877898876394183551 -8877898876394183551
  -8877898876394183551 -8877898876394183551]
 [-8877898876394183551 -8877898876394183551 -8877898876394183551
  -8877898876394183551 -8877898876394183551]
 [-8877898876394183551 -8877898876394183551 -8877898876394183551
  -8877898876394183551 -8877898876394183551]]


In [32]:
# Можно также использовать append
arr_new = np.append(arr_a, arr_b)
print(f'Результат использования append c добавлением .reshape(): \n {arr_new}')

arr_new = np.append(arr_a, arr_b).reshape(6,5)
print(f'\n Результат использования append c добавлением .reshape(): \n {arr_new}')

# или создать трехмерную матрицу (тензор), массив с отдельными матрицами
arr_c = np.array([arr_a, arr_b])
print(f'\n Трехмерный массив: \n {arr_c}')

Результат использования append c добавлением .reshape(): 
 [100 100 100 100 100 100 100 100 100 100 100 100 100 100 100  33  33  33
  33  33  33  33  33  33  33  33  33  33  33  33]

 Результат использования append c добавлением .reshape(): 
 [[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [ 33  33  33  33  33]
 [ 33  33  33  33  33]
 [ 33  33  33  33  33]]

 Трехмерный массив: 
 [[[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]

 [[ 33  33  33  33  33]
  [ 33  33  33  33  33]
  [ 33  33  33  33  33]]]


***Важно*** размерность массивов внутри матрицы должна быть одинаковой!

# Работа с формой массива

## Определение формы массива

In [33]:
print('Трехмерный массив с двумя матрицами')
print(arr_c)
print(f'\n Функция len() покажет нам лишь количество матриц в массиве: {len(arr_c)}')
print(f'\n Мы могли бы обратиться к элементру массива: {len(arr_c[0])}')
print(f'\n Или обратиться к конкретной строке матрицы: {len(arr_c[0][0])}')
print(f'\n Но гораздо лучше использовать атрибут класса shape: {arr_c.shape}')
print(f' 2 - матрицы')
print(f' 3 - строки в каждой матрице')
print(f' 5 - элементов внутри каждой строки')

Трехмерный массив с двумя матрицами
[[[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]

 [[ 33  33  33  33  33]
  [ 33  33  33  33  33]
  [ 33  33  33  33  33]]]

 Функция len() покажет нам лишь количество матриц в массиве: 2

 Мы могли бы обратиться к элементру массива: 3

 Или обратиться к конкретной строке матрицы: 5

 Но гораздо лучше использовать атрибут класса shape: (2, 3, 5)
 2 - матрицы
 3 - строки в каждой матрице
 5 - элементов внутри каждой строки


## Определение количества значений внутри массива

Зная, как найти форму массива мы могли бы просто перемножить значения всех измерений

In [34]:
print(arr_c.shape[0] * arr_c.shape[1] * arr_c.shape[2])

30


In [35]:
# кстати, получить количество измерений можно используя ndim
print(f'Количество измерений в массиве: {arr_c.ndim}')

Количество измерений в массиве: 3


In [36]:
# самый верный способо это .size
print(f'Количество измерений в массиве: {arr_c.size}')

Количество измерений в массиве: 30


## Изменение формы массива .reshape(strings, values)

In [37]:
# Создадим двумерный массив
f1 = np.array([1, 2, 3, 4])
f2 = np.array([5, 6, 7, 8])

# Трехмерный массив
array_f1 = np.array([[f1], [f2]])
print(f'Трехмерный массив, 2 матрицы по 1 строке с 4 элементами: \n {array_f1}')

# 4 строки по 2 элемента (двухмерная матрица)
array_f2 = np.array([[f1], [f2]]).reshape(4, 2)
print(f'\n Двумерный массив, 4 строки по 2 элемента: \n {array_f2}')

# одномерный массив через .size
array_f3 = np.array([[f1], [f2]]).reshape(np.array([[f1], [f2]]).size)
print(f'\n Одномерный массив: \n {array_f3}')

# одномерный массив через .flatten
print(f'\n Самый простой способо использовать array.flatten(): \n {array_f1.flatten()}')

Трехмерный массив, 2 матрицы по 1 строке с 4 элементами: 
 [[[1 2 3 4]]

 [[5 6 7 8]]]

 Двумерный массив, 4 строки по 2 элемента: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

 Одномерный массив: 
 [1 2 3 4 5 6 7 8]

 Самый простой способо использовать array.flatten(): 
 [1 2 3 4 5 6 7 8]


## Транспонирование массива

In [38]:

# cоздадим двумерную матрицу
m_1 = np.array([[1, 1, 1, 1, 1], [0, 0, 0, 0, 0]])
print(f'Матрица имеет исходный вид: \n {m_1}')

# выполним транспониромание
m_t = np.transpose(m_1)
print(f'\n Матрица транспонирована \n {m_t}')

# есть более простой способ чем писать np.transpose. Просто использвать метод класса .Т
m_t_1 = m_1.T
print(f'\n Матрица транспонирована \n {m_t_1}')

# не столь интуитивно работает с одномерными массивами как это может показаться
m_2 = np.array([1, 2, 3, 4, 5])
print(f'\n Одномерный массив имеет исходный вид: \n {m_2}')

m_t_2 = m_2.T
print(f'\n Одномерный массив не был транспонирован \n {m_t_2}')

Матрица имеет исходный вид: 
 [[1 1 1 1 1]
 [0 0 0 0 0]]

 Матрица транспонирована 
 [[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]

 Матрица транспонирована 
 [[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]

 Одномерный массив имеет исходный вид: 
 [1 2 3 4 5]

 Одномерный массив не был транспонирован 
 [1 2 3 4 5]


# Маски

В библиотеке NumPy маски используются для фильтрации массивов на основе заданных условий. Это делается с помощью булевых масок — массивов, состоящих из значений True и False, которые соответствуют элементам исходного массива. Элементы, для которых маска имеет значение True, включаются в итоговый массив, тогда как элементы с False отбрасываются.

In [39]:
# создадим массивы
array_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array_2 = array_1[::-1] # развернем существующий массив в обратном порядке

# выведем результаты
print(f'Массив_1: \n{array_1}')
print(f'Массив_2: \n{array_2}')

Массив_1: 
[ 1  2  3  4  5  6  7  8  9 10]
Массив_2: 
[10  9  8  7  6  5  4  3  2  1]


## boolean маска

In [40]:
# создадим булевую маску
boolean_mask = array_1 >= array_2 # количество элемнтов при сравнении должно бьыть одинаковым

# продемонстрируем результат
print(f'Булевая маска: \n{boolean_mask}')

# применим булевую маску к массиву и посмотрим на результат
print(f'\nВернулись значения, которые соотвествуют условию True булевой маски: \n{array_1[boolean_mask]}')

Булевая маска: 
[False False False False False  True  True  True  True  True]

Вернулись значения, которые соотвествуют условию True булевой маски: 
[ 6  7  8  9 10]


## compare маска

In [41]:
# создадим маску сравнения
compare_mask = array_1 >= 6

# применим к массиву и посмотрим на результат
print(f'Маска сравнения: \n{compare_mask}')

# применим маску сравнения к массиву и посмотрим на результат
print(f'\nВернулись значения, которые соотвествуют условию >= 6 для массива array_1: \n{array_1[compare_mask]}')

Маска сравнения: 
[False False False False False  True  True  True  True  True]

Вернулись значения, которые соотвествуют условию >= 6 для массива array_1: 
[ 6  7  8  9 10]


## маска отрицания

In [42]:
# для демонстрации создадим еще один массив
array_3 = np.array([1, 3, 3, 5, 5, 6, 7, 7, 8, 10])

# отобразим массивы
print(f'Первый массив:\n{array_1}')
print(f'\nВторой массив:\n{array_3}')

# создадим булевую маску отрицания возвращающую True для условия array_1 не равно array_3
negation_mask = ~(array_1 == array_3) # количество элемнтов при сравнении должно бьыть одинаковым

# посмотрим, что возвращает маска
print(f'\nМаска:\n{negation_mask}')
print(array_1[negation_mask])

Первый массив:
[ 1  2  3  4  5  6  7  8  9 10]

Второй массив:
[ 1  3  3  5  5  6  7  7  8 10]

Маска:
[False  True False  True False False False  True  True False]
[2 4 8 9]


In [43]:
# разберем вторйо пример, маска отрицания сравнения

# массив с которым будем работать
print(f'Массив:\n{array_1}')

# маска сравнения отрицаия, вернет True для условия меньше или равно 5
compare_negation_mask = ~(array_1 > 5)
print(f'\nМаска:\n{compare_negation_mask}')

# применим маску к массиву
print(f'\nРезультат - все значения меньше или равны 5:\n{array_1[compare_negation_mask]}')

Массив:
[ 1  2  3  4  5  6  7  8  9 10]

Маска:
[ True  True  True  True  True False False False False False]

Результат - все значения меньше или равны 5:
[1 2 3 4 5]


# Индексация и слайсинг

Ключевые различия: Индексация vs Слайсинг

| **Критерий**            | **Индексация**                        | **Слайсинг**                                |
|-------------------------|---------------------------------------|---------------------------------------------|
| **Что извлекает**       | Конкретный элемент                   | Подмассив (последовательность элементов)    |
| **Синтаксис**           | `array[индекс]`                      | `array[start:stop:step]`                    |
| **Результат**           | Скалярное значение или массив         | Вид (view) массива                          |
| **Изменение оригинала** | Нет (если изменяется результат индексации). | Да, если изменяется срез (без `.copy()`). |
| **Применимость**        | Используется для выбора отдельных элементов | Используется для извлечения диапазонов     |


In [44]:
# определим массив для работы:
array_1 = np.array([1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000])
print(f'Одномерный массив: \n{array_1}')

# определим двумерный массив
array_2 = np.array([[1000, 2000, 3000], [4000, 5000, 6000], [7000, 8000, 9000]])
print(f'\nДвумерный Массив: \n{array_2}')

Одномерный массив: 
[ 1000  2000  3000  4000  5000  6000  7000  8000  9000 10000]

Двумерный Массив: 
[[1000 2000 3000]
 [4000 5000 6000]
 [7000 8000 9000]]


In [45]:
# Индексация одномерных массивов

print(f'Массив: {array_1}')
print(f'\nВернем первое значение в массиве: {array_1[0]}')
print(f'\nВернем последнее значение в массиве: {array_1[-1]}')
print(f'\nВернем все значения после 5000: {array_1[4:]}')
print(f'\nВернем все значения до 5000: {array_1[:4]}')
print(f'\nВернем значения от 2000 до 8000: {array_1[1:8]}')

Массив: [ 1000  2000  3000  4000  5000  6000  7000  8000  9000 10000]

Вернем первое значение в массиве: 1000

Вернем последнее значение в массиве: 10000

Вернем все значения после 5000: [ 5000  6000  7000  8000  9000 10000]

Вернем все значения до 5000: [1000 2000 3000 4000]

Вернем значения от 2000 до 8000: [2000 3000 4000 5000 6000 7000 8000]


In [46]:

# Индексация двумерных массивов
print(f'Массив: \n{array_2}')
print(f'\nВернем первое значение в массиве: {array_2[0, 0]}')
print(f'\nВернем последнее значение в массиве: {array_2[-1, -1]}')
print(f'\nВернем второй элемент второй строки: {array_2[1, 1]}')
print(f'\nВернем вторую строку: {array_2[1, :]}')
print(f'\nВернем второй столбец: {array_2[:, 1]}')
print(f'\nВернем значения от 5000 до 9000: \n{array_2[1:, 1:]}') 

Массив: 
[[1000 2000 3000]
 [4000 5000 6000]
 [7000 8000 9000]]

Вернем первое значение в массиве: 1000

Вернем последнее значение в массиве: 9000

Вернем второй элемент второй строки: 5000

Вернем вторую строку: [4000 5000 6000]

Вернем второй столбец: [2000 5000 8000]

Вернем значения от 5000 до 9000: 
[[5000 6000]
 [8000 9000]]


## .copy

In [47]:

# вызовем исходный массив
print(f'Исходный массив: {array_1}')

# создадим срез на исходном массие и запишем его в новую переменную
slice_1 = array_1[1:5]
print(f'\nСрез: {slice_1}')

# внесем изменения в сам массив, заменим 5000 на 5
slice_1[3] = 0
print(f'\nСрез: {slice_1}')

Исходный массив: [ 1000  2000  3000  4000  5000  6000  7000  8000  9000 10000]

Срез: [2000 3000 4000 5000]

Срез: [2000 3000 4000    0]


In [48]:

# теперь вновь вызовем исходный массив, на основе которого был построен срез
print(f'Исходный массив: {array_1}')

Исходный массив: [ 1000  2000  3000  4000     0  6000  7000  8000  9000 10000]


Поулчается, что срез, созданный на основе массива внес полученные изменения в исходный массив! Чтобы этого не происходило нужно использовать метод .copy()

Повторим все действия но в этот раз воспользуемся методом .copy

In [49]:
# вызовем исходный массив
array_copy = array_2.reshape(-1)
print(f'Исходный массив: {array_copy}')

# создадим срез на исходном массие и запишем его в новую переменную
slice_copy = array_copy[1:5].copy()
print(f'\nСрез: {slice_copy}')

# внесем изменения в сам массив, заменим 5000 на 5
slice_copy[3] = 0
print(f'\nСрез: {slice_copy}')

Исходный массив: [1000 2000 3000 4000 5000 6000 7000 8000 9000]

Срез: [2000 3000 4000 5000]

Срез: [2000 3000 4000    0]


In [50]:
# теперь вновь вызовем исходный массив, на основе которого был построен срез
print(f'Исходный массив: {array_copy}')

Исходный массив: [1000 2000 3000 4000 5000 6000 7000 8000 9000]


Как видно, исходный массив не был изменен благодря использованию метода .copy()

## Индексация практика

In [51]:

# создадим исходную трехмерную матрицу
mat_3d = np.arange(12).reshape(2, 2, 3)
print(f'Исходная матрица: \n{mat_3d}')

# как нам вернуть, например, 5? Это первая матрица, вт орая строка, последний ее элемент
print(f'\nВернем последний элемент второй строки первой матрицы: \n{mat_3d[0, 1, -1]}')
# 0 - первая матрица
# 1 - вторая строка первой матрицы
# -1 первое с конца значения в этой строке

# как нам вернуть, например, вторую колонку в массиве?
print(f'\nВернем вторую колонку в массиве: \n{mat_3d[:, :, 1]}')
# : - выводим все элементы, т.е. все матрицы
# : - нас не интересует строка, фактически нам нужны все строки
# 1 - т.к. нас интересует вторрой столбец, т.е. все вторые значения в каждой строке

# как нам вернуть, например, не только вторую колонку но и третью?
print(f'\nВернем вторую и третью колонку в массиве: \n{mat_3d[:, :, 1:]}')
# : - выводим все элементы, т.е. все матрицы
# : - нас не интересует строка, фактически нам нужны все строки
# 1: - т.к. нас интересует не только вторрой столбец, но и все колонки начиная со второй

# вернем вторую и третью колонку только для первой матрицы
print(f'\nВернем вторую и третью колонку только для первой матрицы: \n{mat_3d[0, :, 1:]}')
# 0 - выводим только первую матрицу
# : - нас не интересует строка, фактически нам нужны все строки
# 1: - т.к. нас интересует не только вторрой столбец, но и все колонки начиная со второй

# выведем первые строчки в обеих матрицах
print(f'\nВернем первые строки в каждой матрице: \n{mat_3d[:, 0, :]}')
# : - выводим все элементы, т.е. все матрицы
# 0 - нас интересует только первая строка
# : - нас интересуют все столбцы

Исходная матрица: 
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

Вернем последний элемент второй строки первой матрицы: 
5

Вернем вторую колонку в массиве: 
[[ 1  4]
 [ 7 10]]

Вернем вторую и третью колонку в массиве: 
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]

Вернем вторую и третью колонку только для первой матрицы: 
[[1 2]
 [4 5]]

Вернем первые строки в каждой матрице: 
[[0 1 2]
 [6 7 8]]


# Индексацяи Fancy

In [86]:
mat_test = np.arange(45).reshape(3, 5, 3)
print(f'Тестовая матрица: \n{mat_test}')

# выведем первую и последнюю строки матриц 2 и 3
mat_test_2 = mat_test[[1,2], [0,4], :].copy()
print(f'\nПервая и последняя строки матриц 2 и 3: \n{mat_test_2}')

# выведем перывй и последний столбцы матриц 1 и 3
mat_test_3 = mat_test[[0,2], :, [0,2]].copy()
print(f'\nПервый и последний столбцы матриц 1 и 3: \n{mat_test_3.T}')

Тестовая матрица: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]]

Первая и последняя строки матриц 2 и 3: 
[[15 16 17]
 [42 43 44]]

Первый и последний столбцы матриц 1 и 3: 
[[ 0 32]
 [ 3 35]
 [ 6 38]
 [ 9 41]
 [12 44]]


## Одновременна Fancy индексация 

In [107]:
# создадим новую матрицу
mat_test_4 = np.arange(16).reshape(4, 4)
print(f'Матрица: \n{mat_test_4}')

# попробуем вывести точечно значения 1, 3, 9 и 11
mat_test_5 = mat_test_4[[0,2],        # перечисляем необходимые строки, это 1 и 3 строка
                        [1,3]].copy() # 2 и 4 колонка

print(f'\nПопробуем вывести точечно значения 1, 3, 9 и 11: \n{mat_test_5}')
# Результат не соответствует ожиданиям. Потмоу что при одновременном использовании fancy для строк и столбцов
# NumPy воспринимает их как координаты. Пересечение 0 и 1 вернет 1, пересечение 1 и 3 вернет 11
print('Не получается')

# как поступать в таком случе? Укажем недостающие координаты
mat_test_5 = mat_test_4[[0,0,2,2],        
                        [1,3,1,3]].copy() 
print(f'\nПопробуем еще раз вывести точечно значения 1, 3, 9 и 11: \n{mat_test_5}')

Матрица: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Попробуем вывести точечно значения 1, 3, 9 и 11: 
[ 1 11]
Не получается

Попробуем еще раз вывести точечно значения 1, 3, 9 и 11: 
[ 1  3  9 11]
